### PR TITLE
Added user router example, and test

### PR DESCRIPTION
**Pull request by wahengchang**

### CODE REVIEW

**Review by RonaldChao — APPROVED** [review]
Understood the flow, everytime to call /users will return a json object.
Need more time to study the unit test code

**Comment by Oscaar13** [comment]
"npm run test" is error, that result show out "sh: ./node_modules/jest/bin/jest.js: No such file or directory", is it caused by my version?

**Comment by RonaldChao** [comment]
Maybe need to install the middleware, jest

On Dec 20, 2017 20:13, "Oscaar13" <notifications@github.com> wrote:

"npm run test" is error, that result show out "sh:
./node_modules/jest/bin/jest.js: No such file or directory", is it caused
by my version?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/4boyss/server/pull/2#issuecomment-353047782>, or mute
the thread

**Comment by Oscaar13** [comment]
Beside jest, Test suite failed to run --> Cannot find module 'node-mocks-http' from 'router.js'
is it middleware problem???

**Comment by wahengchang** [comment]
do 
```
$ npm install 
```

**Review by Oscaar13 — APPROVED** [review]

**Pull request merged**
